export const LOAD_PROFILE_DATA = 'LOAD_PROFILE_DATA';
export const LOAD_PROFILE_DATA_SUCCESS = 'LOAD_PROFILE_DATA_SUCCESS';
export const LOAD_PROFILE_DATA_ERROR = 'LOAD_PROFILE_DATA_ERROR';
export const RESET_OTHER_PROFILE = 'RESET_OTHER_PROFILE';
