export const GET_USER_PROFILE_DATA = 'GET_USER_PROFILE_DATA';
export const GET_USER_PROFILE_DATA_SUCCESS = 'GET_USER_PROFILE_DATA_SUCCESS';
export const GET_USER_PROFILE_DATA_ERROR = 'GET_USER_PROFILE_DATA_ERROR';
export const SHOW_POPUP = 'SHOW_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';

export const ADD_POST = 'ADD_POST';
export const REMOVE_POST = 'REMOVE_POST';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPDATE_AVATAR_LOADING = 'UPDATE_AVATAR_LOADING';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';
