export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const LOG_IN_RESET = 'LOG_IN_RESET';

export const AUTO_LOGIN = 'AUTO_LOGIN';
export const AUTO_LOGIN_ERROR = 'AUTO_LOGIN_ERROR';
export const AUTO_LOGIN_SUCCESSFUL = 'AUTO_LOGIN_SUCCESSFUL';

export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const REGISTRATION_RESET = 'REGISTRATION_RESET';

export const LOGOUT = 'LOGOUT';
