export const LOAD_DIALOGS = 'LOAD_DIALOGS';
export const LOAD_DIALOGS_SUCCESS = 'LOAD_DIALOGS_SUCCESS';
export const LOAD_DIALOGS_ERROR = 'LOAD_DIALOGS_ERROR';
export const CREATE_NEW_DIALOG = 'CREATE_NEW_DIALOG';
export const CREATE_NEW_DIALOG_ERROR = 'CREATE_NEW_DIALOG_ERROR';

export const LOAD_CHAT = 'LOAD_CHAT';
export const OPEN_CHAT = 'OPEN_CHAT';
export const CLOSE_CHAT = 'CLOSE_CHAT';
export const LOAD_CHAT_SUCCESS = 'LOAD_CHAT_SUCCESS';
export const LOAD_CHAT_ERROR = 'LOAD_CHAT_ERROR';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const READ_NEW_MESSAGES = 'READ_NEW_MESSAGES';
